# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1

# =================================
# = Spring
# =================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${BD_URL}:3306/${BD_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${BD_USER}
    password: ${BD_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource

# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: ERROR
    org.flywaydb: ERROR